# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetError(object):
    def setupUi(self, WidgetError):
        WidgetError.setObjectName("WidgetError")
        WidgetError.resize(437, 332)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WidgetError)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Error_listwidget = QtWidgets.QListWidget(WidgetError)
        self.Error_listwidget.setObjectName("Error_listwidget")
        self.horizontalLayout.addWidget(self.Error_listwidget)

        self.retranslateUi(WidgetError)
        QtCore.QMetaObject.connectSlotsByName(WidgetError)

    def retranslateUi(self, WidgetError):
        _translate = QtCore.QCoreApplication.translate
        WidgetError.setWindowTitle(_translate("WidgetError", "Form"))
